### ISSUE TITLE
Update to 2023.2 breaks tailwind iq3 startup

### ISSUE THREAD

**Issue by dmorris1961** [pauln/tailwind-home-assistant#13]
I get this message once I updated HA to 2023.2.

**Logger: homeassistant.setup
Source: setup.py:205
First occurred: 4:42:50 PM (1 occurrences)
Last logged: 4:42:50 PM

Setup failed for custom integration tailwind_iq3: Requirements for tailwind_iq3 not found: ['scapy==2.4.5'].**

Was working fine just before the update.

**Comment by Atreus-X** [comment]
change ['scapy==2.4.5'] to ['scapy==2.5.0'] in line 8 of manifest.json

Also delete the f before the quotes on line 131 in cover.py

That got it back working for me.

**Comment by sellison2** [comment]
Confirmed the above fix worked.

**Comment by twojciac** [comment]
Modifying the manifest.json fixed the issue for me.  Not sure why you'd want to remove the f strings from cover.py, that would remove the ability to get details of an error.

**Comment by dmorris1961** [comment]
Working with the modification to manifest.json.

Thank you.
