### ISSUE TITLE
Integration Broken Following HA 2023.02 Upgrade

### ISSUE THREAD

**Issue by 7uAip6** [pauln/tailwind-home-assistant#18]
Hello,

After upgrading to the 2023.02 version of HA, the integration no longer seems to be working.  I am seeing these two errors on startup and the integration no longer functions.

Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 12:16:27 AM (3 occurrences)
Last logged: 12:16:40 AM

Unable to install package scapy==2.4.5: ERROR: Cannot install scapy==2.4.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 23.0 [notice] To update, run: pip install --upgrade pip

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 12:16:40 AM (1 occurrences)
Last logged: 12:16:40 AM

Setup failed for custom integration tailwind_iq3: Requirements for tailwind_iq3 not found: ['scapy==2.4.5'].

**Comment by pauln** [comment]
Please update the component to 0.4.0 (either via HACS if that's how you installed it, or by manually downloading the latest version and updating the files in your custom_components directory).
