### ISSUE TITLE
HA 2023.2.5 Update: Setup failed for custom integration tailwind_iq3: Requirements for tailwind_iq3 not found

### ISSUE THREAD

**Issue by MitkaR88** [pauln/tailwind-home-assistant#19]
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 11:55:30 (1 occurrences)
Last logged: 11:55:30

Setup failed for custom integration tailwind_iq3: Requirements for tailwind_iq3 not found: ['scapy==2.4.5'].

---

Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 11:55:21 (3 occurrences)
Last logged: 11:55:30

Unable to install package scapy==2.4.5: ERROR: Cannot install scapy==2.4.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by sgmorton** [comment]
Same error here.
Setup failed for custom integration tailwind_iq3: Requirements for tailwind_iq3 not found: ['scapy==2.4.5'].

**Comment by kwil2011** [comment]
Where do you run the pip command from

**Comment by pauln** [comment]
There's no need to run a pip command.  Update the custom component to v0.4.0 via whichever means you installed it (either using HACS or manually downloading and copying it into your custom_components folder), and you should be set.
