### ISSUE TITLE
async_setup_platforms -- deprecated

### ISSUE THREAD

**Issue by ericober** [pauln/tailwind-home-assistant#21]
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

Hello and thanks to the devs for creating this great HACS plugin. I noticed with the 2023.5.2 Home Assistant release that my Tailwind integration was failing at startup. After some research, I found that the async_setup_platform function has been marked as deprecated and set to fail in 2023.3.  It seems that it is now indeed failing. To correct the issue, I have modified "__init__.py" file in HACS - Custom Components - tailwind_iq3, line 74

From:  hass.config_entries.async_setup_platforms(entry, PLATFORMS)
To: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

I restarted Home Assistant and the Tailwind integration seems to be working as expected. Hopefully this is the permanent fix and can be updated in the HACS package for all. 

Thanks

**Comment by pauln** [comment]
@ericober Thanks for the detailed report, and you're welcome.  The deprecation you mention was addressed in v0.4.0 (released Feb 2nd), though I'd suggest updating to v.0.5.0 (released Feb 26th).  If HACS hasn't offered you the update, you should be able to install the update by going to HACS -> Integrations -> Tailwind iQ3, opening the menu in the top right and choosing "Redownload" - if it doesn't offer you the latest version(s), try the "Update information" option in the same menu.

**Comment by ericober** [comment]
@pauln Thank you very much. Pulled the latest as HACS was not giving me the notification for an update.
