### ISSUE TITLE
One Garage Door Stating Incorrect State and Cover Control doesn't work

### ISSUE THREAD

**Issue by rompingfury** [pauln/tailwind-home-assistant#25]
I've got 2 garage door openers working correctly in HomeKit with proper state. In Home Assistant, was able to successfully add and configure both doors, but one of them is showing an incorrect state and doesn't seem to update with garage opening or closing; can't seem to trick it into working or responding to cover control.

**Comment by pauln** [comment]
That's strange; I've got two doors (connected to a single iQ3) and haven't experienced that sort of issue.

A few things come to mind for you to check and/or try (assuming that you have 2 doors connected to a single iQ3):
- Confirm that you have your doors connected to inputs 1 and 2 on the iQ3 unit
- Remove all Tailwind integration entries from Home Assistant, and re-add a single entry with the number of doors set to 2
- If the above don't help, try removing and re-adding with the number of doors set to 3, and see whether your second actual door maps to the third door in the integration

If you've got two iQ3 devices, with one door connected to each, the doors should be connected to input 1 on their respective iQ3 units, and both integration entries should be set to 1 door.  Again, you might want to try re-adding the troublesome entry with the number of doors set to 3 to see whether one of the other doors maps to your actual door.  I only have a single iQ3 unit (I'm a customer, so only have the one unit which I bought); if you do have multiple units and this integration isn't handling that situation properly, would you be willing to help debug (and test potential fixes) by installing unreleased code from GitHub?

**Comment by rompingfury** [comment]
Hey Paul!

Wanted to thank you so much for your reply; it was detailed and
thoughtful, I really appreciate it. When I started reading it dawned on
me that I "do" have two iQ3s - so of course door 2 of the single iQ3
would be stuck in a single state and couldn't be toggled. It was a bit
confusing how to get the second unit in - I thought maybe there would be
another unique code from Tailwind or something; but with some trial and
error I was able to get it working!! So pumped; and thanks again!!

Adam Andries

On November 14, 2023, Paul Nicholls ***@***.***> wrote:
> That's strange; I've got two doors (connected to a single iQ3) and
> haven't experienced that sort of issue.
>
> A few things come to mind for you to check and/or try (assuming that
> you have 2 doors connected to a single iQ3):
>
>  *  Confirm that you have your doors connected to inputs 1 and 2 on
>     the iQ3 unit
>  *  Remove all Tailwind integration entries from Home Assistant, and
>     re-add a single entry with the number of doors set to 2
>  *  If the above don't help, try removing and re-adding with the
>     number of doors set to 3, and see whether your second actual door
>     maps to the third door in the integration
>
> If you've got two iQ3 devices, with one door connected to each, the
> doors should be connected to input 1 on their respective iQ3 units,
> and both integration entries should be set to 1 door. Again, you might
> want to try re-adding the troublesome entry with the number of doors
> set to 3 to see whether one of the other doors maps to your actual
> door. I only have a single iQ3 unit (I'm a customer, so only have the
> one unit which I bought); if you do have multiple units and this
> integration isn't handling that situation properly, would you be
> willing to help debug (and test potential fixes) by installing
> unreleased code from GitHub?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pauln/tailwind-home-
assistant/issues/25#issuecomment-1811629847>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BD66UHTZWNPXJPKCAM3M3Y3YEQHHZAVCNFSM6AAAAAA7LQCR7WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJRGYZDSOBUG4>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by pauln** [comment]
Hi Adam,
Glad to hear that you've got it working.  It's good to know that the integration works with multiple iQ3 units - and that there isn't a separate code for each unit (I guess they must be unique to the Tailwind account, rather than to the device).  Thanks for following up!

- Paul
