### ISSUE TITLE
Retrying setup: Cannot connect to host

### ISSUE THREAD

**Issue by Hoosier-IT** [pauln/tailwind-home-assistant#4]
Retrying setup: Cannot connect to host 192.168.1.165:80 ssl:default [Connect call failed ('192.168.1.165', 80)]
H/w Revision No. V1.3
Model/Fw Ver. IQ3/9.05

**Comment by pauln** [comment]
Per the readme:
> This integration is not final, and currently requires your Tailwind iQ3 device to be running beta firmware.

You'll need to either wait for the firmware update to be finalised/approved/rolled out, or contact Tailwind support to ask to be enrolled in the beta (if they're still accepting new beta users).
