### ISSUE TITLE
Fail to call service error 

### ISSUE THREAD

**Issue by Samkingtx** [pauln/tailwind-home-assistant#6]
Hi,
After firmware update, Tailwind integration does not communicate with Home assistant. I have deleted integration and re added also restarted the Tailwind controller. Now this error appears once I attempt to open the garage door from HA.
Failed to call service cover/open_cover. int' object has no attribute name'

Thank you

**Comment by pauln** [comment]
Hi @Samkingtx - have you updated the integration to the latest version (released just after the V9.95 firmware was)?  There were (unexpected) changes to the local control API, so if you've just updated your firmware from the beta to V9.95, you'll need to first update the integration (via HACS or manually, depending on how you installed the integration initially), then (after restarting Home Assistant to complete the integration update) remove and re-add the integration - following the instructions in the README to get your Local Control Key to enter into the updated integration setup flow.

**Comment by Samkingtx** [comment]
> Hi @Samkingtx - have you updated the integration to the latest version (released just after the V9.95 firmware was)? There were (unexpected) changes to the local control API, so if you've just updated your firmware from the beta to V9.95, you'll need to first update the integration (via HACS or manually, depending on how you installed the integration initially), then (after restarting Home Assistant to complete the integration update) remove and re-add the integration - following the instructions in the README to get your Local Control Key to enter into the updated integration setup flow.


Thank you it works!!
